version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Set up AWS credentials
          command: echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY > ~/.env
      - run:
          name: Initializing the Terraform code
          command: |
            cd ./Non-Modularized/AWS-Serverless-Project
            terraform init
      - run:
          name: Terraform Plan
          command: |
            cd ./Non-Modularized/AWS-Serverless-Project
            terraform plan -var-file variables.tfvars
      - run:
          name: Terraform Apply
          command: |
            cd ./Non-Modularized/AWS-Serverless-Project
            terraform apply --auto-approve -var-file=variables.tfvars

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Set up AWS credentials
          command: echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY > ~/.env
      - run:
          name: Initializing the Terraform code
          command: |
            cd ./Non-Modularized/AWS-Serverless-Project
            terraform init
      - run:
          name: Terraform Destroy
          command: |
            cd ./Non-Modularized/AWS-Serverless-Project
            terraform destroy --auto-approve -var-file variables.tfvars

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy

  destroy-infrastructure:
    jobs:
      - destroy